encSetting:
   encType: Catalog
   encUri: Encs\CATALOG.031
   encLongitude: 121.723234
   encLatitude: 31.350226
   encScale: 320000
   encEnabled: true
radarSettings:
-
   radarName: 崇明岛
   radarLongitude: 121.912592
   radarLatitude: 31.576394
   radarOrientation: 55.0
   radarScale: 275000
   radarMaxDistance: 60
   radarIpAddress: 127.0.0.1
   radarPort: 20101
   isRadarEnabled: true
   isRingsDisplayed: true
   isEchoDisplayed: true
   isOpenGlEchoDisplayed: false
-
   radarName: 世博公园
   radarLongitude: 121.489728
   radarLatitude: 31.192678
   radarOrientation: -85.0
   radarScale: 20000
   radarMaxDistance: 30
   radarIpAddress: 127.0.0.1
   radarPort: 20102
   isRadarEnabled: true
   isRingsDisplayed: false
   isEchoDisplayed: true
   isOpenGlEchoDisplayed: false
-
   radarName: radar3
   radarLongitude: 121.496233
   radarLatitude: 31.375250
   radarOrientation: 27.0
   radarScale: 68750
   radarMaxDistance: 60
   radarIpAddress: 127.0.0.1
   radarPort: 20103
   isRadarEnabled: false
   isRingsDisplayed: false
   isEchoDisplayed: true
   isOpenGlEchoDisplayed: false
-
   radarName: radar4
   radarLongitude: 122.099197
   radarLatitude: 31.416057
   radarOrientation: 34.0
   radarScale: 160000
   radarMaxDistance: 60
   radarIpAddress: 127.0.0.1
   radarPort: 20104
   isRadarEnabled: false
   isRingsDisplayed: false
   isEchoDisplayed: true
   isOpenGlEchoDisplayed: false
-
   radarName: radar5
   radarLongitude: 122.471336
   radarLatitude: 30.780275
   radarOrientation: -76.0
   radarScale: 30000
   radarMaxDistance: 60
   radarIpAddress: 127.0.0.1
   radarPort: 20106
   isRadarEnabled: false
   isRingsDisplayed: false
   isEchoDisplayed: true
   isOpenGlEchoDisplayed: false