encSetting:
   encType: Dir
   encUri: Encs\Hongkong
   encLongitude: 114.059464
   encLatitude: 22.220194
   encScale: 150000
   encEnabled: true
radarSettings:
-
   radarName: 香港岛1
   radarLongitude: 114.200670
   radarLatitude: 22.293878
   radarOrientation: 55.0
   radarScale: 275000
   radarMaxDistance: 60
   radarIpAddress: 234.3.1.1
   radarPort: 20101
   localIp: 127.0.0.1
   isRadarEnabled: true
   isRingsDisplayed: true
   isEchoDisplayed: true
   isOpenGlEchoDisplayed: true
-
   radarName: 大屿山1
   radarLongitude: 113.870939
   radarLatitude: 22.267821
   radarOrientation: -85.0
   radarScale: 20000
   radarMaxDistance: 9
   radarIpAddress: 234.3.1.4
   radarPort: 20102
   localIp: 127.0.0.1
   isRadarEnabled: true
   isRingsDisplayed: false
   isEchoDisplayed: true
   isOpenGlEchoDisplayed: true
-
   radarName: 南丫岛
   radarLongitude: 114.117719
   radarLatitude: 22.181681
   radarOrientation: -85.0
   radarScale: 68750
   radarMaxDistance: 9
   radarIpAddress: 234.3.1.5
   radarPort: 20103
   localIp: 127.0.0.1
   isRadarEnabled: true
   isRingsDisplayed: false
   isEchoDisplayed: true
   isOpenGlEchoDisplayed: true
-
   radarName: 枕箱岛
   radarLongitude: 113.813114
   radarLatitude: 22.134093
   radarOrientation: -87
   radarScale: 160000
   radarMaxDistance: 9
   radarIpAddress: 234.3.1.6
   radarPort: 20104
   localIp: 127.0.0.1
   isRadarEnabled: true
   isRingsDisplayed: false
   isEchoDisplayed: true
   isOpenGlEchoDisplayed: true
-
   radarName: 外伶仃岛
   radarLongitude: 114.035044
   radarLatitude: 22.111725
   radarOrientation: -91.0
   radarScale: 30000
   radarMaxDistance: 9
   radarIpAddress: 234.3.1.7
   radarPort: 20106
   localIp: 127.0.0.1
   isRadarEnabled: true
   isRingsDisplayed: false
   isEchoDisplayed: true
   isOpenGlEchoDisplayed: true